import type { Account } from './types'

// US specialty & generic pharma manufacturers
// Revenue and employee counts verified via Clay (Apr 2026)
// ICP target band: $20M-$75M. Some verified accounts are above/below band
// and tagged accordingly in pains/notes so reps calibrate outreach.
export const SEED_ACCOUNTS: Account[] = [
  // ═══ VERIFIED — ICP CORE ═══
  {id:1,company:"Elite Pharmaceuticals",city:"Northvale, NJ",market:"NJ/NY Metro",vertical:"Specialty Generic · Controlled Substances",rev:"$75M–$200M (Clay)",emp:"64",priority:"High",pe:false,ownership:"OTC: ELTP",pains:["Chargeback claim leakage (844 exceptions)","Controlled-substance SKU reconciliation","Partnered products (TAGI, Glenmark, SunGen) — GTN variance"],cxo:"CEO + Controller",website:"elitepharma.com",liSearch:"elite pharmaceuticals northvale",stage:"Prospect",source:"clay",contacted:false,signals:[]},
  {id:2,company:"Bionpharma",city:"Princeton, NJ",market:"NJ/NY Metro",vertical:"Generic · OTC Softgels",rev:"$10M–$25M (Clay)",emp:"42",priority:"High",pe:false,ownership:"Privately held",pains:["At lower end of ICP — growing fast","Chargeback volume spiking on softgel launches","Small contracts team — judgment calls not scaling"],cxo:"VP Sales & Ops + Sr Dir Corp Dev",website:"bionpharma.com",liSearch:"bionpharma princeton",stage:"Prospect",source:"clay",contacted:false,signals:[]},
  {id:3,company:"Ascend Laboratories",city:"Parsippany, NJ",market:"NJ/NY Metro",vertical:"Generic · Specialty",rev:"$10M–$25M (Clay)",emp:"55",priority:"High",pe:false,ownership:"Alkem Labs (BSE)",pains:["Chargeback leakage on new ANDA launches","Three VPs of National Accounts — channel coordination gap","Parent-division pricing alignment"],cxo:"CFO + VP National Accounts",website:"ascendlaboratories.com",liSearch:"ascend laboratories parsippany",stage:"Prospect",source:"clay",contacted:false,signals:[]},
  {id:4,company:"TAGI Pharma",city:"South Beloit, IL",market:"Midwest",vertical:"Generic · Controlled Substances",rev:"< $10M (Clay · tiny team)",emp:"3",priority:"Medium",pe:false,ownership:"Privately held",pains:["Below ICP but a key partnered-products node for Elite","Ship & debit volume outsized to team size","One-person national-accounts function"],cxo:"VP Sales & Marketing",website:"tagipharma.com",liSearch:"tagi pharma south beloit",stage:"Prospect",source:"clay",contacted:false,signals:[]},

  // ═══ VERIFIED — ABOVE ICP (useful for reference-story positioning) ═══
  {id:5,company:"Heritage Pharmaceuticals (Avet Pharma)",city:"East Brunswick, NJ",market:"NJ/NY Metro",vertical:"Generic Pharmaceuticals",rev:"$75M–$200M (Clay)",emp:"201–500",priority:"High",pe:false,ownership:"Avet Pharma (Emcure)",pains:["Rebranded to Avet Pharma — chargeback system rebuild","Post-DOJ compliance overhead","Lookalike for smaller ICP — same pain at bigger scale"],cxo:"CEO + CFO",website:"heritagepharma.com",liSearch:"heritage pharmaceuticals avet",stage:"Prospect",source:"clay",contacted:false,signals:[]},
  {id:6,company:"Lannett Company",city:"Trevose, PA",market:"Mid-Atlantic",vertical:"Generic Pharmaceuticals · CDMO",rev:"$200M–$500M (Clay)",emp:"494",priority:"High",pe:true,ownership:"Post-bankruptcy PE",pains:["ABOVE ICP — positioning as reference story","Post-restructuring chargeback rebuild","Has dedicated Director, Pricing & Contracts — warm path in"],cxo:"CFO + Director Pricing & Contracts",website:"lannett.com",liSearch:"lannett company trevose",stage:"Prospect",source:"clay",contacted:false,signals:[]},
  {id:7,company:"Tris Pharma",city:"Monmouth Junction, NJ",market:"NJ/NY Metro",vertical:"Specialty CNS · Branded Generics",rev:"$200M–$500M (Clay)",emp:"490",priority:"High",pe:false,ownership:"Privately held",pains:["ABOVE ICP — Model N / IntegriChain territory","Controlled-substance chargeback workflow","Director of Market Access Ops — our buyer persona"],cxo:"CFO + Director Market Access Ops",website:"trispharma.com",liSearch:"tris pharma monmouth junction",stage:"Prospect",source:"clay",contacted:false,signals:[]},

  // ═══ UNVERIFIED — needs Clay enrichment before outreach ═══
  {id:8,company:"SunGen Pharma",city:"Princeton, NJ",market:"NJ/NY Metro",vertical:"Generic Pharmaceuticals",rev:"Unverified — enrich via Clay",emp:"Unverified",priority:"High",pe:false,ownership:"Privately held",pains:["Partnered with Elite Pharmaceuticals — validates pain","Chargeback processing volume spike post-ANDA","Needs contact enrichment before outreach"],cxo:"— (enrich)",website:"sungenpharma.com",liSearch:"sungen pharma princeton",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:9,company:"Epic Pharma",city:"Laurelton, NY",market:"NJ/NY Metro",vertical:"Generic Oral Solids",rev:"Unverified — enrich via Clay",emp:"Unverified",priority:"High",pe:true,ownership:"Humanwell Healthcare",pains:["Chargeback dispute backlog with Cardinal","Needs contact enrichment before outreach","PE-backed — recap trigger event possible"],cxo:"— (enrich)",website:"epicpharma.com",liSearch:"epic pharma laurelton",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:10,company:"Chartwell Pharmaceuticals",city:"Congers, NY",market:"NJ/NY Metro",vertical:"Specialty Generic",rev:"Unverified — enrich via Clay",emp:"Unverified",priority:"High",pe:false,ownership:"Privately held",pains:["Ship & debit program setup complexity","Needs contact enrichment before outreach","340B eligibility validation"],cxo:"— (enrich)",website:"chartwellrx.com",liSearch:"chartwell pharmaceuticals congers",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:11,company:"Rising Pharmaceuticals",city:"Saddle Brook, NJ",market:"NJ/NY Metro",vertical:"Generic Pharmaceuticals",rev:"Unverified — enrich via Clay",emp:"Unverified",priority:"High",pe:true,ownership:"Aceto / PE-backed",pains:["Post-recap chargeback cleanup","Needs contact enrichment before outreach","Contracts analyst turnover trigger"],cxo:"— (enrich)",website:"risingpharma.com",liSearch:"rising pharmaceuticals saddle brook",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:12,company:"Aurolife Pharma",city:"Dayton, NJ",market:"NJ/NY Metro",vertical:"Generic Pharmaceuticals",rev:"$1M–$5M (Clay · likely US ops only)",emp:"73",priority:"Medium",pe:false,ownership:"Aurobindo (NSE)",pains:["Small US-division revenue — India parent handles most","Parent-division chargeback coordination gap","IRA Medicare negotiation exposure"],cxo:"— (enrich US leads)",website:"aurolifepharma.com",liSearch:"aurolife pharma dayton",stage:"Prospect",source:"clay",contacted:false,signals:[]},
  {id:13,company:"Zydus Pharmaceuticals US",city:"Pennington, NJ",market:"NJ/NY Metro",vertical:"Generic · Specialty",rev:"Unverified — enrich via Clay",emp:"Unverified",priority:"High",pe:false,ownership:"Zydus Lifesciences (NSE)",pains:["US-India chargeback reconciliation","Needs contact enrichment before outreach","Big Three dispute backlog"],cxo:"— (enrich US CFO + Contracts Dir)",website:"zydususa.com",liSearch:"zydus pharmaceuticals pennington",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:14,company:"Slayback Pharma",city:"Princeton, NJ",market:"NJ/NY Metro",vertical:"Specialty Injectables",rev:"Unverified — enrich via Clay",emp:"Unverified",priority:"High",pe:false,ownership:"KKR / Azurity Pharma",pains:["Injectable chargeback complexity","Needs contact enrichment before outreach","Hospital IDN contracts"],cxo:"— (enrich)",website:"slaybackpharma.com",liSearch:"slayback pharma princeton",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:15,company:"Rhodes Pharmaceuticals",city:"Coventry, RI",market:"New England",vertical:"Specialty · Controlled Substances",rev:"Unverified — enrich via Clay",emp:"Unverified",priority:"High",pe:false,ownership:"Purdue-affiliated",pains:["DEA-regulated chargeback compliance","Needs contact enrichment before outreach","Audit-ready credit memo trail"],cxo:"— (enrich)",website:"rhodespharma.com",liSearch:"rhodes pharmaceuticals coventry",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:16,company:"Arbor Pharmaceuticals",city:"Atlanta, GA",market:"Southeast",vertical:"Specialty Pediatrics",rev:"Unverified — enrich via Clay",emp:"Unverified",priority:"High",pe:false,ownership:"Azurity (private)",pains:["Pediatric specialty chargeback setup","Needs contact enrichment before outreach","GTN reserves on specialty SKUs"],cxo:"— (enrich)",website:"arborpharma.com",liSearch:"arbor pharmaceuticals atlanta",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:17,company:"Lehigh Valley Technologies",city:"Allentown, PA",market:"Mid-Atlantic",vertical:"Specialty Generic",rev:"Unverified — enrich via Clay",emp:"Unverified",priority:"Medium",pe:false,ownership:"Privately held",pains:["Small-team chargeback processing","Needs contact enrichment before outreach","Spreadsheet-based 844 intake"],cxo:"— (enrich)",website:"lvhealth.com",liSearch:"lehigh valley technologies allentown",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:18,company:"Granules Pharmaceuticals",city:"Chantilly, VA",market:"Mid-Atlantic",vertical:"Generic Pharmaceuticals",rev:"Unverified — enrich via Clay",emp:"Unverified",priority:"High",pe:false,ownership:"Granules India (NSE)",pains:["US chargeback coordination with India parent","Needs contact enrichment before outreach","Big Three dispute backlog"],cxo:"— (enrich US lead)",website:"granulesindia.com",liSearch:"granules pharmaceuticals chantilly",stage:"Prospect",source:"manual",contacted:false,signals:[]},
]
