import type { Account } from './types'

// Texas manufacturers with strong distributor networks and ship & debit complexity
export const SEED_ACCOUNTS: Account[] = [
  // ═══ ELECTRONICS / SEMICONDUCTORS — sell through Arrow, Avnet, Digi-Key, Mouser ═══
  {id:1,company:"Texas Instruments",city:"Dallas",market:"Dallas/DFW",vertical:"Semiconductors",rev:"$18B+",emp:"30000+",priority:"High",pe:false,ownership:"NASDAQ: TXN",pains:["Ship & debit across 100+ distributors","Design-in rebate tracking","Global distributor price protection"],cxo:"VP Channel Sales + CFO",website:"ti.com",liSearch:"texas instruments dallas",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:2,company:"NXP Semiconductors — Austin",city:"Austin",market:"Austin",vertical:"Semiconductors / Automotive",rev:"$13B+",emp:"3000+ (Austin)",priority:"High",pe:false,ownership:"NASDAQ: NXPI",pains:["Ship & debit reconciliation delays","Distributor inventory visibility","Price protection claims processing"],cxo:"VP Americas Distribution + CFO",website:"nxp.com",liSearch:"nxp semiconductors austin",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:3,company:"Flex (Flextronics)",city:"Austin",market:"Austin",vertical:"Electronics Contract Mfg",rev:"$26B+",emp:"5000+ (Austin)",priority:"High",pe:false,ownership:"NASDAQ: FLEX",pains:["Multi-tier distributor pricing","Component rebate tracking","Ship & debit across EMS channels"],cxo:"VP Supply Chain + CFO",website:"flex.com",liSearch:"flex austin",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:4,company:"Benchmark Electronics",city:"Angleton TX",market:"Houston",vertical:"Electronics Contract Mfg",rev:"$2.8B",emp:"2000+",priority:"High",pe:false,ownership:"NYSE: BHE",pains:["Distributor special pricing agreements","Ship & debit claims volume","Revenue recognition on rebates"],cxo:"CFO + VP Procurement",website:"bench.com",liSearch:"benchmark electronics texas",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:5,company:"Vicor — Austin Design Center",city:"Austin",market:"Austin",vertical:"Power Electronics",rev:"$400M+",emp:"200+ (Austin)",priority:"High",pe:false,ownership:"NASDAQ: VICR",pains:["Distributor price protection windows","Design-win ship & debit","Channel conflict between direct and distis"],cxo:"VP Sales + Channel Director",website:"vicorpower.com",liSearch:"vicor austin",stage:"Prospect",source:"manual",contacted:false,signals:[]},

  // ═══ INDUSTRIAL / MRO — sell through Grainger, MSC, Fastenal, HD Supply ═══
  {id:6,company:"Pelican Products",city:"Denton TX",market:"Dallas/DFW",vertical:"Industrial Protective Cases",rev:"$600M+",emp:"1500+",priority:"High",pe:true,ownership:"Bain Capital",pains:["Ship & debit with industrial distributors","Volume rebate tier tracking","Distributor vs direct pricing conflicts"],cxo:"VP Sales + CFO",website:"pelican.com",liSearch:"pelican products denton texas",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:7,company:"Enerpac Tool Group",city:"Houston",market:"Houston",vertical:"Industrial Tools & Equipment",rev:"$600M+",emp:"500+ (Houston)",priority:"High",pe:false,ownership:"NYSE: EPAC",pains:["Ship & debit across 200+ distributors","Special pricing authorization workflow","Rebate accrual accuracy"],cxo:"VP Channel + CFO",website:"enerpac.com",liSearch:"enerpac houston",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:8,company:"Dover Corporation — ESG",city:"Houston",market:"Houston",vertical:"Industrial Equipment OEM",rev:"$2B+ (segment)",emp:"3000+",priority:"High",pe:false,ownership:"NYSE: DOV",pains:["Multi-brand ship & debit programs","Distributor inventory reconciliation","Price protection claim disputes"],cxo:"VP Distribution + Division CFO",website:"dovercorporation.com",liSearch:"dover corporation houston",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:9,company:"Forum Energy Technologies",city:"Houston",market:"Houston",vertical:"Oilfield Equipment OEM",rev:"$700M+",emp:"2000+",priority:"Medium",pe:false,ownership:"NYSE: FET",pains:["Ship & debit with energy distributors","SPA management across regions","Rebate revenue leakage"],cxo:"VP Sales + CFO",website:"f-e-t.com",liSearch:"forum energy technologies houston",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:10,company:"NOV (National Oilwell Varco)",city:"Houston",market:"Houston",vertical:"Oilfield & Industrial Equipment",rev:"$8B+",emp:"30000+",priority:"High",pe:false,ownership:"NYSE: NOV",pains:["Global ship & debit complexity","Distributor tier pricing automation","Debit memo reconciliation at scale"],cxo:"VP Commercial + SVP Finance",website:"nov.com",liSearch:"NOV houston",stage:"Prospect",source:"manual",contacted:false,signals:[]},

  // ═══ CHEMICALS — sell through Brenntag, Univar, IMCD ═══
  {id:11,company:"Huntsman Corporation",city:"The Woodlands TX",market:"Houston",vertical:"Specialty Chemicals",rev:"$6B+",emp:"9000+",priority:"High",pe:false,ownership:"NYSE: HUN",pains:["Ship & debit with chemical distributors","Volume-based rebate tier complexity","Distributor commission reconciliation"],cxo:"VP Sales + CFO",website:"huntsman.com",liSearch:"huntsman corporation woodlands",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:12,company:"Kraton Corporation",city:"The Woodlands TX",market:"Houston",vertical:"Specialty Polymers",rev:"$2B+",emp:"2000+",priority:"High",pe:true,ownership:"Apollo / DL Chemical",pains:["Ship & debit across polymer distributors","Rebate accrual vs actuals gaps","Price protection on volatile raw materials"],cxo:"CFO + VP Distribution Sales",website:"kraton.com",liSearch:"kraton corporation woodlands",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:13,company:"Altivia Corporation",city:"Houston",market:"Houston",vertical:"Specialty Chemicals",rev:"$80M–$160M",emp:"200–400",priority:"High",pe:false,ownership:"Privately held",pains:["Ship & debit with regional distributors","Contract pricing management","Volume discount reconciliation"],cxo:"CFO + CEO",website:"altivia.com",liSearch:"altivia corporation houston",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:14,company:"Ascend Performance Materials",city:"Houston",market:"Houston",vertical:"Nylon & Engineered Plastics",rev:"$3B+",emp:"2800+",priority:"High",pe:true,ownership:"SK Capital Partners",pains:["Multi-segment ship & debit programs","Distributor price protection windows","Global rebate program management"],cxo:"CFO + VP Commercial",website:"ascendmaterials.com",liSearch:"ascend performance materials houston",stage:"Prospect",source:"manual",contacted:false,signals:[]},

  // ═══ HVAC / BUILDING PRODUCTS — sell through Ferguson, Winsupply,?"ABCs" ═══
  {id:15,company:"Lennox International",city:"Richardson TX",market:"Dallas/DFW",vertical:"HVAC OEM",rev:"$4.7B",emp:"10000+",priority:"High",pe:false,ownership:"NYSE: LII",pains:["Ship & debit with HVAC wholesalers","Dealer incentive program complexity","Co-op advertising fund tracking"],cxo:"VP Distribution + CFO",website:"lennoxinternational.com",liSearch:"lennox international richardson",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:16,company:"CSW Industrials",city:"Dallas",market:"Dallas/DFW",vertical:"HVAC & Industrial Products OEM",rev:"$800M+",emp:"3000+",priority:"High",pe:false,ownership:"NASDAQ: CSWI",pains:["Ship & debit through HVAC distributors","Multi-product rebate programs","Distributor vs contractor pricing tiers"],cxo:"CRO + CFO",website:"cswindustrials.com",liSearch:"CSW industrials dallas",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:17,company:"Welbilt (Ali Group)",city:"Dallas",market:"Dallas/DFW",vertical:"Commercial Foodservice Equipment",rev:"$1.5B+",emp:"4000+",priority:"Medium",pe:false,ownership:"Ali Group (private)",pains:["Ship & debit with foodservice distributors","Dealer rebate tracking","Special pricing agreement volume"],cxo:"VP Channel Sales + CFO",website:"welbilt.com",liSearch:"welbilt dallas",stage:"Prospect",source:"manual",contacted:false,signals:[]},

  // ═══ FASTENERS / COMPONENTS — sell through Fastenal, Würth, HD Supply ═══
  {id:18,company:"Haynes Wire Company",city:"Houston",market:"Houston",vertical:"Wire & Cable Mfg",rev:"$100M+",emp:"300+",priority:"Medium",pe:false,ownership:"Privately held",pains:["Ship & debit with electrical distributors","Price protection on commodity swings","Volume rebate tier management"],cxo:"VP Sales + Controller",website:"hayneswire.com",liSearch:"haynes wire houston",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:19,company:"Sievert Larsen",city:"Houston",market:"Houston",vertical:"Industrial Fasteners & Fittings",rev:"$50M–$100M",emp:"200+",priority:"Medium",pe:false,ownership:"Privately held",pains:["Ship & debit with MRO distributors","SPA pricing for large OEM accounts","Rebate claim processing delays"],cxo:"VP Sales + CFO",website:"sievertlarsen.com",liSearch:"sievert larsen houston",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:20,company:"Hose Master — Texas",city:"Houston",market:"Houston",vertical:"Industrial Hose Assemblies",rev:"$100M+",emp:"400+",priority:"Medium",pe:false,ownership:"Privately held",pains:["Ship & debit through industrial distributors","Custom assembly pricing to channel","Distributor stock rotation credits"],cxo:"VP Sales + Controller",website:"hosemaster.com",liSearch:"hose master houston texas",stage:"Prospect",source:"manual",contacted:false,signals:[]},
]
