import type { BdrEvent } from './types'

export const SEED_EVENTS: BdrEvent[] = [
  // AUSTIN
  {id:'a1',name:'ARMA Safety Summit',dates:'Mar 5, 2026 · 8am–1pm',location:'Austin, TX (Georgetown)',type:'Conference',category:'conference',why:'Half-day OSHA trends and workplace safety seminar for manufacturers.',relevance:'Medium',url:'https://arma-tx.org/events',attending:false,notes:'Good networking. Falcon Structures, Athena, Cumberland are ARMA members.'},
  {id:'a2',name:'ARMA Luncheon — AI in Manufacturing',dates:'Mar 24, 2026 · 11:30am',location:'Austin, TX (Sheraton Georgetown)',type:'Meetup',category:'meetup',why:'Andrew Peters (Circuit AI) on AI integration in manufacturing. Registration 11:30, lunch 12pm.',relevance:'High',url:'https://arma-tx.org/events',attending:false,notes:'Join ARMA ($250/yr). Network with local mfg leaders.'},
  {id:'a2b',name:'ARMA Spring Golf Tournament',dates:'Apr 16, 2026 · Afternoon',location:'Austin, TX (Avery Ranch Golf Club)',type:'Meetup',category:'meetup',why:'150+ players. Shotgun start. Best relationship-building event of the year.',relevance:'High',url:'https://arma-tx.org/events',attending:false,notes:'Register early. Invite target account contacts as guests.'},
  {id:'a3',name:'ARMA Luncheons (Quarterly)',dates:'Quarterly · check arma-tx.org',location:'Austin, TX (Round Rock / Georgetown)',type:'Meetup',category:'meetup',why:'30-50 Austin manufacturing executives. High signal, low noise.',relevance:'High',url:'https://arma-tx.org/events',attending:false,notes:'Check ARMA site for Q2/Q3 dates. Embassy Suites or Sheraton.'},
  {id:'a4',name:'Capital Factory — Open Coworking Day',dates:'Every Tuesday · 5th floor',location:'Austin, TX (Capital Factory)',type:'Co-working',category:'meetup',why:'Weekly drop-in. Ideas spark, connections happen. Austin tech-meets-mfg crowd.',relevance:'Medium',url:'https://opencoworking.capitalfactory.com/',attending:false,notes:'Show up 2x/month. Great for Falcon, Blue Sage intros.'},
  {id:'a5',name:'InnoTech Austin',dates:'May 12, 2026',location:'Austin, TX (Palmer Events Center)',type:'Conference',category:'conference',why:'Full day of networking, tech demos, and professional development.',relevance:'Medium',url:'',attending:false,notes:'Tech-focused but good for meeting IT leaders at mfg companies.'},
  {id:'a6',name:'Austin Small Business Expo',dates:'Oct 29, 2026 · 10am–5pm',location:'Austin, TX (Palmer Events Center)',type:'Expo',category:'conference',why:'Founder-owned businesses. Blue Sage Capital portfolio intros.',relevance:'Medium',url:'https://www.thesmallbusinessexpo.com/city/austin/',attending:false,notes:'Attend with David.'},
  // HOUSTON
  {id:'h1',name:'OTC 2026 (Offshore Technology Conference)',dates:'May 4–7, 2026',location:'Houston, TX (NRG Park)',type:'Trade Show',category:'trade_show',why:'Massive energy + industrial event. Oil States, CIRCOR, Altivia ICP all attend.',relevance:'High',url:'https://2026.otcnet.org/',attending:false,notes:'Book meetings with Oil States (Cindy Taylor) and CIRCOR contacts in advance.'},
  {id:'h2',name:'Connected Worker & Smart Manufacturing Summit',dates:'Jun 11–12, 2026',location:'Houston, TX',type:'Conference',category:'conference',why:'VPs, directors, ops leaders. AI, IoT, connected worker platforms. Perfect for RCA pitch.',relevance:'High',url:'https://www.key-notion.com/the-connected-worker-and-smart-manufacturing-summit-2026',attending:false,notes:'Attend both days. Target ops leaders.'},
  {id:'h3',name:'URTeC 2026',dates:'Jun 22–24, 2026',location:'Houston, TX (GRB Convention Center)',type:'Conference',category:'conference',why:'Unconventional resources + technology. Oil States, energy-adjacent mfg contacts.',relevance:'Medium',url:'',attending:false,notes:'Relevant for energy manufacturing ICP.'},
  {id:'h4',name:'Houston Technology Summit',dates:'May 6, 2026',location:'Houston, TX (Hyatt Regency West)',type:'Conference',category:'conference',why:'IT and technology leaders. 1-day summit on modern IT priorities.',relevance:'Medium',url:'',attending:false,notes:'Meet CIOs/IT Directors at Houston mfg companies.'},
  {id:'h5',name:'SPE ATCE 2026',dates:'Oct 21–23, 2026',location:'Houston, TX',type:'Conference',category:'conference',why:'Society of Petroleum Engineers. Largest technical gathering for energy professionals.',relevance:'Medium',url:'',attending:false,notes:'Energy sector overlap with industrial mfg.'},
  {id:'h6',name:'AMPP Annual Conference + Expo',dates:'Mar 15–19, 2026',location:'Houston, TX (GRB Convention Center)',type:'Conference',category:'conference',why:'Materials performance, corrosion, coatings. Altivia, Vibrantz, Ascend adjacent.',relevance:'Medium',url:'',attending:false,notes:'Relevant for specialty chemicals ICP.'},
  // DALLAS / FORT WORTH
  {id:'d1',name:'AEA International Convention',dates:'Mar 23–26, 2026',location:'Dallas, TX (Hilton Anatole)',type:'Trade Show',category:'trade_show',why:'Avionics industry — manufacturers, distributors, technicians. DFW manufacturing leaders.',relevance:'High',url:'',attending:false,notes:'Network with Arcosa, Conner Industries, DFW manufacturers.'},
  {id:'d2',name:'American Electronics & High-Tech Mfg Summit',dates:'Jun 16–17, 2026',location:'Dallas, TX (Hilton Anatole)',type:'Conference',category:'conference',why:'Electronics and high-tech manufacturing leaders. Advanced automation.',relevance:'High',url:'',attending:false,notes:'SabeRex, Q2 Holdings contacts relevant.'},
  {id:'d3',name:'IntraLogisteX',dates:'Sep 16–17, 2026',location:'Dallas, TX (Kay Bailey Hutchison Center)',type:'Trade Show',category:'trade_show',why:'Logistics and supply chain operations. Warehouse efficiency and automation.',relevance:'Medium',url:'',attending:false,notes:'Supply chain overlap with manufacturing ops.'},
  {id:'d4',name:'DFW Small Business Expo',dates:'Nov 4, 2026 · 10am–5pm',location:'Dallas, TX (Kay Bailey Hutchison Center)',type:'Expo',category:'conference',why:'Mid-market business owners. Arcosa, Conner, Sky Island portfolio.',relevance:'Medium',url:'https://www.thesmallbusinessexpo.com/city/dallas/',attending:false,notes:'Attend with David.'},
  // NATIONAL
  {id:'n1',name:'SAMA Annual Conference 2026',dates:'May 18–20, 2026',location:'Phoenix, AZ (Arizona Biltmore)',type:'Association',category:'conference',why:'Premier SAM event. 45+ sessions. VP Sales, CRO community. Top Nteli event.',relevance:'High',url:'https://strategicaccounts.org/event/2026-sama-annual-conference/',attending:false,notes:'Target 8 meetings with TX manufacturing VP Sales.'},
  {id:'n2',name:'IMTS 2026',dates:'Sep 14–19, 2026',location:'Chicago, IL (McCormick Place)',type:'Trade Show',category:'trade_show',why:'1M+ sq ft. Capital equipment and precision manufacturing. Register before Aug 1.',relevance:'High',url:'https://www.imts.com',attending:false,notes:'Biggest manufacturing show. International registration free.'},
  {id:'n3',name:'FABTECH 2026',dates:'Oct 21–23, 2026',location:'Las Vegas, NV (LVCC)',type:'Trade Show',category:'trade_show',why:'Largest North American metal fabrication event. Free registration before Oct 16.',relevance:'High',url:'https://www.fabtechexpo.com',attending:false,notes:'Host dinner for 10-12 TX manufacturing prospects.'},
  {id:'n4',name:'CSIA Executive Conference',dates:'May 13–16, 2026',location:'Orlando, FL',type:'Association',category:'conference',why:'Control Systems Integrators — excellent referral partners for RCA deals.',relevance:'Medium',url:'https://www.controlsys.org',attending:false,notes:'Target 3-5 SI partnership conversations.'},
]
