import type { Account } from './types'

// US specialty & generic pharma manufacturers, $20M-$75M revenue
// Selling through Cardinal / McKesson / Cencora (Big Three)
// Ship & debit / chargeback contracts with GPOs, IDNs, 340B, Medicaid
// Reference: Elite Pharmaceuticals (Northvale, NJ)
export const SEED_ACCOUNTS: Account[] = [
  // ═══ NJ / NY METRO — pharma hub ═══
  {id:1,company:"Elite Pharmaceuticals",city:"Northvale, NJ",market:"NJ/NY Metro",vertical:"Specialty Generic · Controlled Substances",rev:"$30M–$50M",emp:"150–300",priority:"High",pe:false,ownership:"OTC: ELTP",pains:["Chargeback claim leakage (844 exceptions)","Controlled-substance SKU reconciliation","GTN variance on partnered products"],cxo:"CFO + Director, Contracts",website:"elitepharma.com",liSearch:"elite pharmaceuticals northvale",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:2,company:"TAGI Pharma",city:"Lebanon, TN",market:"Southeast",vertical:"Generic · Controlled Substances",rev:"$40M–$75M",emp:"100–250",priority:"High",pe:false,ownership:"Privately held",pains:["Ship & debit program management at scale","340B duplicate-discount remediation","Dispute workflow backlog"],cxo:"CFO + VP Contracts",website:"tagipharma.com",liSearch:"tagi pharma lebanon",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:3,company:"SunGen Pharma",city:"Princeton, NJ",market:"NJ/NY Metro",vertical:"Generic Pharmaceuticals",rev:"$30M–$60M",emp:"100–200",priority:"High",pe:false,ownership:"Privately held",pains:["Chargeback processing volume spike post-ANDA","Reserve calculation accuracy","Wholesaler 844 intake on spreadsheets"],cxo:"CFO + Director Contracts",website:"sungenpharma.com",liSearch:"sungen pharma princeton",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:4,company:"Bionpharma",city:"Princeton, NJ",market:"NJ/NY Metro",vertical:"Specialty Generic",rev:"$50M–$75M",emp:"150–300",priority:"High",pe:false,ownership:"Privately held",pains:["GTN variance from auditor questions","Chargeback accrual reserve accuracy","Contract-price validation on Big Three"],cxo:"CFO + VP Finance",website:"bionpharma.com",liSearch:"bionpharma princeton",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:5,company:"Epic Pharma",city:"Laurelton, NY",market:"NJ/NY Metro",vertical:"Generic Oral Solids",rev:"$40M–$70M",emp:"200–400",priority:"High",pe:true,ownership:"Humanwell Healthcare",pains:["Chargeback dispute backlog with Cardinal","EDI 844/845 validation manual","Medicaid rebate reconciliation"],cxo:"CFO + Contracts Director",website:"epicpharma.com",liSearch:"epic pharma laurelton",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:6,company:"Chartwell Pharmaceuticals",city:"Congers, NY",market:"NJ/NY Metro",vertical:"Specialty Generic",rev:"$25M–$50M",emp:"100–200",priority:"High",pe:false,ownership:"Privately held",pains:["Ship & debit program setup complexity","340B eligibility validation","Wholesaler dispute aging"],cxo:"CFO + VP Operations",website:"chartwellrx.com",liSearch:"chartwell pharmaceuticals congers",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:7,company:"Heritage Pharmaceuticals",city:"East Brunswick, NJ",market:"NJ/NY Metro",vertical:"Generic Pharmaceuticals",rev:"$50M–$75M",emp:"200–400",priority:"High",pe:false,ownership:"Emcure subsidiary",pains:["Post-DOJ chargeback compliance overhead","Contract renewal & eligibility automation","Credit memo posting to NetSuite"],cxo:"CFO + Chief Compliance",website:"heritagepharma.com",liSearch:"heritage pharmaceuticals east brunswick",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:8,company:"Rising Pharmaceuticals",city:"Saddle Brook, NJ",market:"NJ/NY Metro",vertical:"Generic Pharmaceuticals",rev:"$30M–$60M",emp:"100–200",priority:"High",pe:true,ownership:"Aceto / PE-backed",pains:["Post-recap chargeback cleanup","Ship & debit accrual under restated financials","Contracts analyst turnover"],cxo:"CFO + VP Contracts",website:"risingpharma.com",liSearch:"rising pharmaceuticals saddle brook",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:9,company:"Ascend Laboratories",city:"Montvale, NJ",market:"NJ/NY Metro",vertical:"Generic · Specialty",rev:"$40M–$70M",emp:"150–300",priority:"High",pe:false,ownership:"Alkem Labs (BSE)",pains:["Chargeback leakage on new ANDA launches","GPO contract price validation","Wholesaler 844 exception volume"],cxo:"CFO + Director Contracts",website:"ascendlaboratories.com",liSearch:"ascend laboratories montvale",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:10,company:"Aurolife Pharma",city:"East Windsor, NJ",market:"NJ/NY Metro",vertical:"Generic Pharmaceuticals",rev:"$50M–$75M",emp:"200–400",priority:"High",pe:false,ownership:"Aurobindo (NSE)",pains:["Parent-division chargeback coordination","IRA Medicare negotiation exposure","Reserve true-up accuracy"],cxo:"CFO + VP Finance US",website:"aurolifepharma.com",liSearch:"aurolife pharma east windsor",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:11,company:"Zydus Pharmaceuticals US",city:"Pennington, NJ",market:"NJ/NY Metro",vertical:"Generic · Specialty",rev:"$60M–$75M (US div)",emp:"250–400",priority:"High",pe:false,ownership:"Zydus Lifesciences (NSE)",pains:["US-India chargeback reconciliation","Big Three dispute backlog","340B duplicate-discount remediation"],cxo:"US CFO + VP Contracts",website:"zydususa.com",liSearch:"zydus pharmaceuticals pennington",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:12,company:"Slayback Pharma",city:"Princeton, NJ",market:"NJ/NY Metro",vertical:"Specialty Injectables",rev:"$25M–$50M",emp:"80–150",priority:"High",pe:false,ownership:"KKR / Azurity Pharma",pains:["Injectable chargeback complexity","Hospital IDN contracts manual","Ship & debit at launch scale"],cxo:"CFO + VP Contracts",website:"slaybackpharma.com",liSearch:"slayback pharma princeton",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:13,company:"Tris Pharma",city:"Monmouth Junction, NJ",market:"NJ/NY Metro",vertical:"Specialty CNS",rev:"$50M–$75M",emp:"200–400",priority:"High",pe:false,ownership:"Privately held",pains:["Controlled-substance chargeback workflow","Specialty wholesaler dispute aging","GTN variance on branded generics"],cxo:"CFO + Director Contracts",website:"trispharma.com",liSearch:"tris pharma monmouth junction",stage:"Prospect",source:"manual",contacted:false,signals:[]},

  // ═══ PA / NE ═══
  {id:14,company:"Lannett Company",city:"Trevose, PA",market:"Mid-Atlantic",vertical:"Generic Pharmaceuticals",rev:"$50M–$75M",emp:"200–400",priority:"High",pe:true,ownership:"Post-bankruptcy PE",pains:["Post-restructuring chargeback rebuild","Contract master data cleanup","Reserve calculation under new CFO"],cxo:"CFO + VP Contracts",website:"lannett.com",liSearch:"lannett company trevose",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:15,company:"Rhodes Pharmaceuticals",city:"Coventry, RI",market:"New England",vertical:"Specialty · Controlled Substances",rev:"$40M–$75M",emp:"150–300",priority:"High",pe:false,ownership:"Purdue-affiliated",pains:["DEA-regulated chargeback compliance","Controlled-substance eligibility checks","Audit-ready credit memo trail"],cxo:"CFO + Chief Compliance",website:"rhodespharma.com",liSearch:"rhodes pharmaceuticals coventry",stage:"Prospect",source:"manual",contacted:false,signals:[]},

  // ═══ SE / SW ═══
  {id:16,company:"Arbor Pharmaceuticals",city:"Atlanta, GA",market:"Southeast",vertical:"Specialty Pediatrics",rev:"$50M–$75M",emp:"200–400",priority:"High",pe:false,ownership:"Azurity (private)",pains:["Pediatric specialty chargeback setup","Hub-program financial reconciliation","GTN reserves on specialty SKUs"],cxo:"CFO + VP Contracts",website:"arborpharma.com",liSearch:"arbor pharmaceuticals atlanta",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:17,company:"Lehigh Valley Technologies",city:"Allentown, PA",market:"Mid-Atlantic",vertical:"Specialty Generic",rev:"$20M–$40M",emp:"80–150",priority:"High",pe:false,ownership:"Privately held",pains:["Small-team chargeback processing","Spreadsheet-based 844 intake","Contract setup bottleneck"],cxo:"CFO + Owner",website:"lvhealth.com",liSearch:"lehigh valley technologies allentown",stage:"Prospect",source:"manual",contacted:false,signals:[]},
  {id:18,company:"Granules Pharmaceuticals",city:"Chantilly, VA",market:"Mid-Atlantic",vertical:"Generic Pharmaceuticals",rev:"$50M–$75M",emp:"200–400",priority:"High",pe:false,ownership:"Granules India (NSE)",pains:["US chargeback coordination with India parent","Big Three dispute backlog","New ANDA claim volume spike"],cxo:"US CFO + Director Contracts",website:"granulesindia.com",liSearch:"granules pharmaceuticals chantilly",stage:"Prospect",source:"manual",contacted:false,signals:[]},
]
