import type { BdrEvent } from './types'

// Events for specialty pharma: chargebacks, pricing & contracting, distribution, 340B
export const SEED_EVENTS: BdrEvent[] = [
  // ═══ PHARMA PRICING & CONTRACTING ═══
  {id:'p1',name:'CBI Pharmaceutical Contracting & Pricing Summit',dates:'Feb 24–26, 2026',location:'Philadelphia, PA',type:'Conference',category:'conference',why:'Premier event for GTN, chargebacks, rebates, and ship & debit in pharma. CFOs, VP Contracts, Directors of Chargebacks attend. Model N & IntegriChain run booths — catch unhappy customers.',relevance:'High',url:'https://www.cbinet.com',attending:false,notes:'Must attend. Target Elite, TAGI, Bionpharma, Heritage, Epic contacts. Book 1:1s in advance.'},
  {id:'p2',name:'CBI Chargeback & Rebate Operations Summit',dates:'Apr 14–15, 2026',location:'Orlando, FL',type:'Conference',category:'conference',why:'All-day focus on 844/845 EDI, dispute workflows, accrual methodology. Directors of Contracts & Chargebacks are the core audience.',relevance:'High',url:'https://www.cbinet.com',attending:false,notes:'Tactical event. Contracts directors openly discuss their pain. Host a dinner.'},
  {id:'p3',name:'CBI GTN & Revenue Management Conference',dates:'Jun 16–17, 2026',location:'Princeton, NJ',type:'Conference',category:'conference',why:'Walking distance from Bionpharma, SunGen, Slayback, Zydus. GTN variance, reserve calculation, audit prep — all our sweet spots.',relevance:'High',url:'https://www.cbinet.com',attending:false,notes:'Highest density of NJ pharma CFOs and VP Finance in one place. Target list: Elite, Bionpharma, SunGen, Heritage, Aurolife, Zydus, Slayback.'},

  // ═══ DISTRIBUTION / CHANNEL ═══
  {id:'d1',name:'HDA Distribution Management Conference',dates:'Mar 8–11, 2026',location:'Orlando, FL (Gaylord Palms)',type:'Conference',category:'conference',why:'Healthcare Distribution Alliance — Cardinal, McKesson, Cencora execs attend. Manufacturers and wholesalers talk ship & debit directly.',relevance:'High',url:'https://www.hda.org',attending:false,notes:'Book meetings with Big Three distribution partners. Network with manufacturer peers.'},
  {id:'d2',name:'HDA Business & Leadership Conference',dates:'Jun 8–10, 2026',location:'Colorado Springs, CO',type:'Conference',category:'conference',why:'Strategic-level HDA event. CFOs and COOs of specialty pharma manufacturers attend alongside Big Three leadership.',relevance:'High',url:'https://www.hda.org',attending:false,notes:'Senior audience. Invite CFO targets to Nteli-hosted breakfast.'},

  // ═══ GENERIC PHARMA ═══
  {id:'g1',name:'AAM Annual Meeting (Generic Drug Forum)',dates:'Feb 10–12, 2026',location:'Washington, DC',type:'Conference',category:'conference',why:'Association for Accessible Medicines. CEOs of generic manufacturers — our entire ICP attends. Chargeback leakage is an open wound here.',relevance:'High',url:'https://accessiblemeds.org',attending:false,notes:'Most valuable event of the year. Target: Heritage, Epic, Lannett, Rising, Aurolife, Zydus, Granules CEOs.'},
  {id:'g2',name:'GPhA CMC Workshop',dates:'Jun 23–25, 2026',location:'Bethesda, MD',type:'Conference',category:'conference',why:'Generic drug manufacturing and CMC. Networking event for ops leaders at generic manufacturers.',relevance:'Medium',url:'https://accessiblemeds.org',attending:false,notes:'More technical than financial. Good for ops-side relationships.'},

  // ═══ 340B / GOVERNMENT PROGRAMS ═══
  {id:'t1',name:'340B Coalition Winter Conference',dates:'Feb 17–19, 2026',location:'San Diego, CA',type:'Conference',category:'conference',why:'340B eligibility, duplicate-discount remediation, and compliance. Pharma manufacturers and 340B covered entities together.',relevance:'High',url:'https://www.340bcoalition.org',attending:false,notes:'340B duplicate-discount is a recurring trigger event for our prospects. High signal.'},
  {id:'t2',name:'Informa Medicaid Drug Rebate Summit',dates:'Sep 14–16, 2026',location:'Baltimore, MD',type:'Conference',category:'conference',why:'Medicaid rebate reconciliation, state pricing programs, IRA Medicare negotiation prep.',relevance:'High',url:'https://www.informaconnect.com',attending:false,notes:'CFOs and VP Government Programs at specialty pharma.'},

  // ═══ INDUSTRY / DCAT ═══
  {id:'i1',name:'DCAT Week',dates:'Mar 16–19, 2026',location:'New York, NY (Hilton Midtown)',type:'Trade Show',category:'trade_show',why:'Drug, Chemical & Associated Technologies. Biggest pharma networking week of the year. Manufacturers, suppliers, distributors.',relevance:'High',url:'https://www.dcat.org',attending:false,notes:'NJ/NY pharma hub. Walk-in distance for Elite, Bionpharma, SunGen, Slayback, Tris contacts. Book member meetings in DCAT portal.'},
  {id:'i2',name:'BIO International Convention',dates:'Jun 1–4, 2026',location:'San Diego, CA',type:'Trade Show',category:'trade_show',why:'Biotech + pharma. Larger than our ICP but good for partnering-story conversations and deal-flow intelligence.',relevance:'Medium',url:'https://convention.bio.org',attending:false,notes:'Better for later-stage relationships. Not primary prospecting venue.'},

  // ═══ FINANCE / PE ═══
  {id:'f1',name:'LifeSci Advisors Healthcare Conference',dates:'Jan 13–16, 2026',location:'Miami, FL',type:'Conference',category:'conference',why:'PE operating partners and specialty pharma CFOs in a single room. IRA, chargebacks, and PE recap activity are active topics.',relevance:'High',url:'https://www.lifesciadvisors.com',attending:false,notes:'PE recap and new-CFO triggers are our strongest buy signals. This is where those conversations start.'},
  {id:'f2',name:'JPMorgan Healthcare Conference',dates:'Jan 12–15, 2026',location:'San Francisco, CA',type:'Conference',category:'conference',why:'Biggest healthcare investor event globally. Side meetings are where deals happen — our prospects spend the week doing back-to-back sessions.',relevance:'Medium',url:'https://www.jpmorgan.com/healthcare',attending:false,notes:'Too big for booth. Get invited to side events. Heritage, Lannett, Epic CFOs typically attend.'},

  // ═══ LOCAL / NJ PHARMA ═══
  {id:'n1',name:'NJ Pharma CFO Forum',dates:'Quarterly · NJ Tech Council',location:'Princeton, NJ',type:'Meetup',category:'meetup',why:'Small, invite-only gathering of NJ specialty pharma CFOs. High-signal relationships.',relevance:'High',url:'',attending:false,notes:'Request an intro via David. Most of our top 10 targets are members.'},
  {id:'n2',name:'HBA (Healthcare Businesswomen\u2019s Association) NJ Chapter',dates:'Monthly · 3rd Thursday',location:'Princeton / Parsippany, NJ',type:'Meetup',category:'meetup',why:'Many Director-level contracts professionals at specialty pharma attend. Informal, relationship-focused.',relevance:'Medium',url:'https://www.hbanet.org',attending:false,notes:'Good for Director, Contracts & Chargebacks buyer persona.'},

  // ═══ RESIDENTIAL / EXEC DINNERS ═══
  {id:'e1',name:'Nteli Private Dinner — Princeton CFOs',dates:'Host quarterly · TBD',location:'Princeton, NJ',type:'Dinner',category:'dinner',why:'Our own hosted dinner. 6-8 specialty pharma CFOs over dinner at Agricola or Elements. Intimate, peer-driven.',relevance:'High',url:'',attending:false,notes:'Run by Kathir. Invite Elite, Bionpharma, SunGen, Slayback, Tris CFOs. Topic: "What chargeback leakage actually costs you."'},
]
